#!/bin/bash
# 竞技鹅 OS 手动推送脚本

echo "======================================"
echo "  竞技鹅 OS GitHub 推送指南"
echo "======================================"
echo ""
echo "由于需要 GitHub 认证，请按以下步骤手动推送："
echo ""
echo "1️⃣ 创建 GitHub 仓库"
echo "   访问：https://github.com/new"
echo "   仓库名：jingjigo-os"
echo "   可见性：Public"
echo "   ❌ 不要添加 README/.gitignore"
echo ""
echo "2️⃣ 推送代码（选择一种方式）"
echo ""
echo "   方式 A - HTTPS + Token（推荐）:"
echo "   cd /root/.openclaw/workspace/mission-control"
echo "   git remote set-url origin https://YOUR_TOKEN@github.com/257394/jingjigo-os.git"
echo "   git push -u origin main --force"
echo ""
echo "   方式 B - SSH 密钥:"
echo "   cd /root/.openclaw/workspace/mission-control"
echo "   git remote set-url origin git@github.com:257394/jingjigo-os.git"
echo "   git push -u origin main --force"
echo ""
echo "3️⃣ 获取 GitHub Token"
echo "   访问：https://github.com/settings/tokens"
echo "   生成新 Token (classic)"
echo "   勾选：repo 权限"
echo "   复制 Token 替换上面的 YOUR_TOKEN"
echo ""
echo "======================================"
echo "  文件已准备就绪"
echo "======================================"
echo ""
echo "📦 已创建文件:"
echo "   ✅ install.sh - 自动安装脚本"
echo "   ✅ README.md - 项目文档"
echo "   ✅ package.json - 项目配置"
echo ""
echo "🚀 一键安装命令（推送后）:"
echo "   curl -fsSL https://raw.githubusercontent.com/257394/jingjigo-os/main/install.sh | bash"
echo ""
